### ISSUE TITLE
Crash by loading your newest Version of the 1.12.2 SurvivalInc mod with Xearons Minimap and Worldmap 

### ISSUE THREAD

**Issue by Titoo8899** [Enginecrafter77/SurvivalInc#3] opened 2020-05-05 10:07 UTC
Hi, 
the your Mod crash the game. The Mod SurvivalInc is incompatible in this new Version with the Xearons Minamap und Worldmap. Please check the Crash Report. I have with the Owner of the Mod Xearons Minimap and Worldmap read and he write it is the incompatible of your newest Version of your mod. I have with the SurvivalInc and the Version for the last Version of your mod play and this have work only this new Version SurvivalInc-1.0.0-1.12.2 have this Problem. I hope you can fix this.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CamPatchingLoader (CMDCam+v1.4.7+mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.12_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  Players List Core Plugin (oxygen-players-list-1.12.2-0.11.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  McLib core mod (mclib-1.0.4-1.12.2.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  LoadingPlugin (Xaeros_Minimap_20.10.0_Forge_1.12.jar)
  HCASM (HammerCore-1.12.2-2.0.6.17.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 5/4/20 10:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Xaero's World Map (xaeroworldmap)
Caused by: java.lang.NullPointerException
	at enginecrafter77.survivalinc.season.SeasonData.load(SeasonData.java:67)
	at enginecrafter77.survivalinc.season.LeafColorer.func_186720_a(LeafColorer.java:51)
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
	at xaero.map.MapWriter.updateGrassColor(MapWriter.java:475)
	at xaero.map.MapWriter.<init>(MapWriter.java:79)
	at xaero.map.WorldMap.load(WorldMap.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1012740576 bytes (965 MB) / 8791261184 bytes (8384 MB) up to 13958643712 bytes (13312 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx13G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 113 mods loaded, 112 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version               | Source                                          | Signature                                |
	|:----- |:--------------------------- |:--------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                   | 1.12.2                | minecraft.jar                                   | None                                     |
	| UCHI  | mcp                         | 9.42                  | minecraft.jar                                   | None                                     |
	| UCHI  | FML                         | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                       | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | creativecoredummy           | 1.0.0                 | minecraft.jar                                   | None                                     |
	| UCHI  | smoothfontcore              | mc1.12.2-2.1.1        | minecraft.jar                                   | None                                     |
	| UCHI  | xaerominimap_core           | 1.12.2-1.0            | minecraft.jar                                   | None                                     |
	| UCHI  | dsurroundcore               | 3.5.4.3               | minecraft.jar                                   | None                                     |
	| UCHI  | smoothfont                  | mc1.12.2-2.1.1        | SmoothFont-mc1.12.2-2.1.1.jar                   | None                                     |
	| UCHI  | securitycraft               | v1.8.14.1             | [1.12.2]+SecurityCraft+v1.8.14.1.jar            | None                                     |
	| UCHI  | versionchecker              | @VERSION@             | [1.12.2]+VersionChecker-1.4.0.jar               | None                                     |
	| UCHI  | asphaltmod                  | 2.3.4                 | AsphaltMod 2.3.4.jar                            | None                                     |
	| UCHI  | betterplacement             | 1.0.0-1               | BetterPlacement-1.0.0-1.jar                     | None                                     |
	| UCHI  | blur                        | 1.0.4-14              | Blur-1.0.4-14.jar                               | None                                     |
	| UCHI  | carpentersblocks            | 3.4.0-poc.6           | Carpenter's Blocks v3.4.0-poc.6 - MC 1.12.2.jar | None                                     |
	| UCHI  | ctm                         | MC1.12.2-1.0.0.29     | CTM-MC1.12.2-1.0.0.29.jar                       | None                                     |
	| UCHI  | chisel                      | MC1.12.2-0.2.1.35     | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| UCHI  | chiselsandbits              | 14.33                 | chiselsandbits-14.33.jar                        | None                                     |
	| UCHI  | cleanview                   | 1.12.2-v1c            | CleanView-1.12.2-v1c.jar                        | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHI  | cmdcam                      | 1.4.0                 | CMDCam+v1.4.7+mc1.12.2.jar                      | None                                     |
	| UCHI  | coloredredstone             | 1.3.2                 | Colored+Redstone-1.3.2.jar                      | None                                     |
	| UCHI  | unknownlibs                 | 1.0.3                 | UnknownLibs-1.0.3.jar                           | None                                     |
	| UCHI  | colorhealthbar              | 1.3.0                 | Colored-Health-Bar-1.3.0.jar                    | None                                     |
	| UCHI  | craftstudioapi              | 1.0.0                 | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHI  | opframe                     | 1.4.0                 | OnlinePicFrame_v1.4.38_mc1.12.2.jar             | None                                     |
	| UCHI  | creativecore                | 1.10.0                | CreativeCore_v1.10.12_mc1.12.2.jar              | None                                     |
	| UCHI  | customnpcs                  | 1.12                  | CustomNPCs_1.12.2-(01Oct19).jar                 | None                                     |
	| UCHI  | ptrmodellib                 | 1.0.4                 | PTRLib-1.0.4.jar                                | None                                     |
	| UCHI  | props                       | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                      | None                                     |
	| UCHI  | df-roads                    | 1.5.2-mc1.12.2        | df-roads-1.5.2-mc1.12.2.jar                     | None                                     |
	| UCHI  | dynamiclights               | 1.4.9                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_onfire        | 1.0.7                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_creepers      | 1.0.6                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_dropitems     | 1.1.0                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_entityclasses | 1.0.1                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_mobequipment  | 1.1.0                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_flamearrows   | 1.0.1                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_floodlights   | 1.0.3                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_otherplayers  | 1.0.9                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | dynamiclights_theplayer     | 1.1.3                 | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHI  | fantasticlib                | 1.12.2.033            | FantasticLib-1.12.2.033.jar                     | None                                     |
	| UCHI  | dynamicstealth              | 1.12.2.102            | DynamicStealth-1.12.2.102.jar                   | None                                     |
	| UCHI  | eki                         | 1.2.1                 | EkiMod-1.2.1.jar                                | None                                     |
	| UCHI  | mclib                       | 1.0.4                 | mclib-1.0.4-1.12.2.jar                          | None                                     |
	| UCHI  | emoticons                   | 0.4.3                 | emoticons-0.4.3-1.12.2.jar                      | None                                     |
	| UCHI  | fancymenu                   | 1.0.1                 | fancymenu_1.0.1_MC_1.12-1.12.2.jar              | None                                     |
	| UCHI  | fcl                         | 1.XII.51              | Fexcraft+Common+Library-1.XII.51.jar            | None                                     |
	| UCHI  | tmt                         | 1.5                   | Fexcraft+Common+Library-1.XII.51.jar            | None                                     |
	| UCHI  | flycommand                  | 3.0                   | FlyCommandMod-1.12.2-3.0.jar                    | None                                     |
	| UCHI  | freelook                    | 1.2.2                 | FreeLook-1.2.2.jar                              | None                                     |
	| UCHI  | jei                         | 4.15.0.275            | jei_1.12.2-4.15.0.275.jar                       | None                                     |
	| UCHI  | ftblib                      | 5.4.7.0               | FTBLib-5.4.7.0.jar                              | None                                     |
	| UCHI  | itemfilters                 | 1.0.3.12              | ItemFilters-1.0.3.12.jar                        | None                                     |
	| UCHI  | ftbquests                   | 1.8.0.238             | FTBQuests-1.8.0.238.jar                         | None                                     |
	| UCHI  | ftbmoney                    | 1.1.0.42              | FTBMoney-1.1.0.42.jar                           | None                                     |
	| UCHI  | furenikusroads              | 1.1.6                 | Furenikus+Roads+1.1.6.jar                       | None                                     |
	| UCHI  | gamemodekeybind             | Definitive            | GamemodeKeybind.jar                             | None                                     |
	| UCHI  | gymcraft_1122               | 1.12.2                | GymCraft+1.12.2.jar                             | None                                     |
	| UCHI  | hammercore                  | 2.0.6.17              | HammerCore-1.12.2-2.0.6.17.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| UCHI  | the_hospital_mod            | 1.0.0                 | Hospital+Mod+1.12.2+(14.23.5.2768).jar          | None                                     |
	| UCHI  | lieutenant                  | 1.4                   | lieutenant-1.5.jar                              | None                                     |
	| UCHI  | lightingwand                | 1.0.5                 | LightingWand-1.12.2-1.0.5.jar                   | None                                     |
	| UCHI  | locks                       | 2.2.1                 | Locks-2.2.1.jar                                 | None                                     |
	| UCHI  | mcwdoors                    | 1.0                   | mcw-doors-1.0.0-mc1.12.2.jar                    | None                                     |
	| UCHI  | mcwroofs                    | 1.0.2                 | mcw-roofs-1.0.2-mc1.12.2.jar                    | None                                     |
	| UCHI  | mcwwindows                  | 1.0                   | mcw-windows-1.0.0-mc1.12.2.jar                  | None                                     |
	| UCHI  | new_road                    | 1.0.0                 | More+Road+V3.0.0.jar                            | None                                     |
	| UCHI  | movingelevators             | 1.2.14                | movingelevators-1.2.14-mc1.12.jar               | None                                     |
	| UCHI  | uteamcore                   | 2.2.5.147             | u_team_core-1.12.2-2.2.5.147.jar                | None                                     |
	| UCHI  | musicplayer                 | 2.0.7.64              | music_player-1.12.2-2.0.7.64.jar                | None                                     |
	| UCHI  | mw                          | 1.11.7.7              | mw-1.11.7.7_mc1.12.2.jar                        | None                                     |
	| UCHI  | notes                       | 1.1.1                 | Notes-1.12-1.1.1.jar                            | None                                     |
	| UCHI  | oxygen_core                 | 0.11.0                | oxygen-core-1.12.2-0.11.0.jar                   | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_cp_ftb               | 0.11.0                | oxygen-cp-ftb-money-1.12.2-0.11.0.jar           | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_dailyrewards         | 0.11.0                | oxygen-daily-rewards-1.12.2-0.11.0.jar          | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_exchange             | 0.11.0                | oxygen-exchange-1.12.2-0.11.0.jar               | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_friendslist          | 0.11.0                | oxygen-friends-list-1.12.2-0.11.0.jar           | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_groups               | 0.11.0                | oxygen-groups-1.12.2-0.11.0.jar                 | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_mail                 | 0.11.0                | oxygen-mail-1.12.2-0.11.0.jar                   | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_market               | 0.11.0                | oxygen-market-1.12.2-0.11.0.jar                 | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_menu                 | 0.11.0                | oxygen-menu-1.12.2-0.11.0.jar                   | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_merchants            | 0.11.0                | oxygen-merchants-1.12.2-0.11.0.jar              | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_pinteraction         | 0.11.0                | oxygen-player-interaction-1.12.2-0.11.0.jar     | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_playerslist          | 0.11.0                | oxygen-players-list-1.12.2-0.11.0.jar           | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_shop                 | 0.11.0                | oxygen-shop-1.12.2-0.11.0.jar                   | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | oxygen_teleportation        | 0.11.0                | oxygen-teleportation-1.12.2-0.11.0.jar          | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHI  | pointless_tech_two          | 2                     | Pointless+Tech+2_1.12.2.jar                     | None                                     |
	| UCHI  | pointlesstech               | Version 1             | Pointless_Tech_V1_1.12.2.jar                    | None                                     |
	| UCHI  | zblock                      | 1.2020.05.02          | pushable_puzzle_blocks-1.2020.05.02.jar         | None                                     |
	| UCHI  | rcroads                     | 0.3.0                 | RC+Roads+0.3.0.jar                              | None                                     |
	| UCHI  | redstonepaste               | 1.7.5                 | redstonepaste-mc1.12-1.7.5.jar                  | None                                     |
	| UCHI  | roadworks                   | 2.0.0 Beta            | Roadworks+2-1.12.2-1.0.jar                      | None                                     |
	| UCHI  | rockhounding_core           | 3.22                  | rockhounding_core-1.12.2-3.22.jar               | None                                     |
	| UCHI  | gbook                       | 2.8.3                 | Guidebook-1.12.2-2.8.3.jar                      | None                                     |
	| UCHI  | rockhounding_rocks          | 1.12.2-3.20           | rockhounding_rocks-1.12.2-3.20.jar              | None                                     |
	| UCHI  | scm                         | 1.0.00c-Beta          | SCM-v1.12.2-1.0.00c-Beta.jar                    | None                                     |
	| UCHI  | screenbrowser               | 2r                    | ScreenshotBrowser-1.12.2-2r.jar                 | None                                     |
	| UCHI  | shw                         | 1.1                   | shw-1.1.1.jar                                   | None                                     |
	| UCHI  | simpledifficulty            | 0.2.4                 | SimpleDifficulty-1.12.2-0.2.4.jar               | None                                     |
	| UCHI  | smoothzoom                  | 1.0                   | Smooth+Zoom-1.0.jar                             | None                                     |
	| UCHI  | smooth-scrolling-everywhere | 1.1                   | smooth-scrolling-everywhere-1.1.jar             | None                                     |
	| UCHI  | stadiumcraft                | 1.0.0                 | StadiumCraft+1.12.2+Version+1.jar               | None                                     |
	| UCHI  | survivalinc                 | 1.0.0-1.12.2          | SurvivalInc-1.0.0-1.12.2.jar                    | None                                     |
	| UCHI  | teamsmod                    | 1.4                   | teamsmod-1.5.jar                                | None                                     |
	| UCHI  | warp_mod                    | 1.0.0                 | Warp+Mod-1.3.4.jar                              | None                                     |
	| UCHI  | worldedit                   | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None                                     |
	| UCHI  | xaerominimap                | 20.10.0               | Xaeros_Minimap_20.10.0_Forge_1.12.jar           | None                                     |
	| UCHEE | xaeroworldmap               | 1.5.7                 | XaerosWorldMap_1.5.7_Forge_1.12.jar             | None                                     |
	| UCH   | xercapaint                  | 1.12.2-1.3            | xercapaint-1.12.2-1.3.jar                       | None                                     |
	| UCH   | orelib                      | 3.5.2.3               | OreLib-1.12.2-3.5.2.3.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | dsurround                   | 3.5.4.3               | DynamicSurroundings-1.12.2-3.5.4.3.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | nofog                       | 1.12.2-1.12.2-1.0.3.0 | NoFog-1.12.2b3.jar                              | 0bf221d944c89aaf3ccb7b8315148f222be50739 |
	| UD    | mclib_core                  | 1.0.4                 | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
CamPatchingLoader (CMDCam+v1.4.7+mc1.12.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
CreativePatchingLoader (CreativeCore_v1.10.12_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Players List Core Plugin (oxygen-players-list-1.12.2-0.11.0.jar)
  austeretony.oxygen_playerslist.common.core.PlayersListClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  bre.smoothfont.asm.Transformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
LoadingPlugin (Xaeros_Minimap_20.10.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
HCASM (HammerCore-1.12.2-2.0.6.17.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	HammerCore Debug Information: 
Dependent Mods: None.

**Comment by Enginecrafter77** [comment] 2020-05-05 12:10
Hi! Thanks for reporting! Unfortunately, I can't investigate very far in this case since Xaero's Minimap is closed source, so I can't really backtrack the code to find the issue. But from a quick look, it seems that Xaero's Minimap is passing null pointer as world reference to the call in my function, which is crashing since it tries to actually load data from the null world. I think I may add a quick&dirty check to avoid this crash, but I am going to try to dive into this a little bit deeper.

**Comment by Enginecrafter77** [comment] 2020-05-05 14:31
Okay, so the issue seems resolved. Xaero's Minimap had no conflicts with this mod prior to reporting this issue. The mod that was causing the issue was Xaero's World Map, since it was trying to get the foliage colors of various blocks <ins>before</ins> the world was even started, so obviously there was no world reference. I fixed it by adding a little check into the code to check if the world is by any means null, and if it is so, just skip the seasonal modifier. The issue is fixed in release v1.0.1.

**Closed by Enginecrafter77** 2020-05-05 14:31 UTC
Labels: crash
