### ISSUE TITLE
Crash with Better Foliage

### ISSUE THREAD

**Issue by mxnmnm** [Enginecrafter77/SurvivalInc#12] opened 2020-05-21 02:12 UTC
https://gist.github.com/mxnmnm/ab9ebe01990c4f43bc2b58bb69c96b9f

**Comment by Enginecrafter77** [comment] 2020-05-22 23:15
To be honest, this is outright strange. I used the standard particle spawning method, as you can see in the second and third stacktrace entry. But the first entry suggests that Better Foliage is somehow messing with the standard methods. Anyways, I will look at it.

**Comment by Enginecrafter77** [comment] 2020-06-14 23:22
Looking retrospectively at this issue, I think it's not relevant anymore. The offending code referenced in the crash was removed anyways in https://github.com/Enginecrafter77/SurvivalInc/commit/bc6233889423483b2d8d15b97732ea4d946a452b. I tested it with Better Foliage v1.8.4 and Survival Inc. [latest commit to master], and I couldn't reproduce the crash. As such, I am closing this issue.

**Closed by Enginecrafter77** 2020-06-14 23:22 UTC
Labels: crash
